/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package project5;
import javax.swing.JFrame;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class IFrame extends javax.swing.JInternalFrame {

    private boolean isEdit = false;
    private int totalHarga;
    /**
     * Creates new form IFrame
     */
    public IFrame() {
        initComponents();
        tampil_data();
    }
    
    public void reset() {
        cbBarang.setSelectedIndex(0);
        eKode.setText(null);
        eHarga.setText(null);
        eNama.setText(null);
        eJumlah.setText(null);
        eTotal.setText(null);
        eBayar.setText(null);
        eKembalian.setText(null);
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("pilbar");
        tabel.addColumn("kode");
        tabel.addColumn("harga");
        tabel.addColumn("namapembeli");
        tabel.addColumn("jumlah");
        tabel.addColumn("total");
        tabel.addColumn("bayar");
        tabel.addColumn("kembalian");
        
        try {
            java.sql.Connection conn = project5.PROJECT5.koneksiDB();
            String query = "select * from pemesanan1";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                Object [] row = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
            
            tblBarang.setModel(tabel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        eKode = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        eNama = new javax.swing.JTextField();
        eJumlah = new javax.swing.JTextField();
        eTotal = new javax.swing.JTextField();
        eBayar = new javax.swing.JTextField();
        eKembalian = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barang", "Kode", "Harga", "Nama", "Jumlah", "Total", "Bayar", "Kembali"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 520, 210));

        btnHapus.setBackground(new java.awt.Color(214, 212, 190));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 80, 30));

        btnKeluar.setBackground(new java.awt.Color(214, 212, 190));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tab1.jpg"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        tbData.addTab("Data Penjualan", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel3.setText("INPUT DATA PENJUALAN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Pilih Barang");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Kode Barang");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Harga Barang");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Nama Pembeli");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Pembelian");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Harga");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Total Pembayaran");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("kembalian");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText(":");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 30, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText(":");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 30, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 30, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText(":");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 30, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText(":");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 30, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText(":");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 20, 20));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText(":");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 30, 20));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText(":");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 30, 20));

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan", "Buku", "Bolpoin", "Pensil", "Penggaris", "Penghapus", "Sticky Note", " " }));
        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });
        jPanel3.add(cbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, -1));

        eKode.setEditable(false);
        jPanel3.add(eKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, -1));

        eHarga.setEditable(false);
        jPanel3.add(eHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, -1));
        jPanel3.add(eNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 150, -1));
        jPanel3.add(eJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, -1));

        eTotal.setEditable(false);
        jPanel3.add(eTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 140, -1));
        jPanel3.add(eBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 150, -1));
        jPanel3.add(eKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, -1));

        btnReset.setBackground(new java.awt.Color(214, 212, 190));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(214, 212, 190));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        jPanel3.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 30));

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel3.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tab1.jpg"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbData.addTab("Pembayaran", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbData))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBarang.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                try {
                    String namabarangToDelete = (String) tblBarang.getValueAt(selectedRow, 3);
                    String sql = "DELETE FROM pemesanan1 WHERE namapembeli = ?";
                    java.sql.Connection conn = (java.sql.Connection) project5.PROJECT5.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, namabarangToDelete);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    reset();
                    tampil_data();
                    isEdit = false;
                    btnSimpan.setText("Simpan");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        String namabarang = (String) cbBarang.getSelectedItem();
        String kode = eKode.getText();
        String harga = eHarga.getText();
        String namapembeli = eNama.getText();
        String jumlah = eJumlah.getText();
        String total = eTotal.getText();
        String bayar = eBayar.getText();
        String kembali = eKembalian.getText();

        if (namabarang.equals("Pilihan") || kode.isEmpty() || harga.isEmpty() || namapembeli.isEmpty() || jumlah.isEmpty() || total.isEmpty() || bayar.isEmpty() || kembali.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom data terlebih dahulu.");
        } else {
            if (isEdit) {
                int selectedRow = tblBarang.getSelectedRow();
                String namapembeliToUpdate = (String) tblBarang.getValueAt(selectedRow, 3); // Ganti dengan kolom yang sesuai
                String sql = "UPDATE pemesanan1 SET namabarang = ?, kode = ?, harga = ?, namapembeli = ?, jumlah = ?, total = ?, bayar = ?, kembalian = ? WHERE namapembeli = ?";
                java.sql.Connection conn = project5.PROJECT5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namabarang);
                pst.setString(2, kode);
                pst.setString(3, harga);
                pst.setString(4, namapembeli);
                pst.setString(5, jumlah);
                pst.setString(6, total);
                pst.setString(7, bayar);
                pst.setString(8, kembali);
                pst.setString(9, namapembeliToUpdate);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
                isEdit = false;
                btnSimpan.setText("Simpan");
            } else {
                // Mode Simpan: Simpan data baru
                String sql = "INSERT INTO pemesanan1 (namabarang, kode, harga, namapembeli, jumlah, total, bayar, kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                java.sql.Connection conn = project5.PROJECT5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namabarang);
                pst.setString(2, kode);
                pst.setString(3, harga);
                pst.setString(4, namapembeli);
                pst.setString(5, jumlah);
                pst.setString(6, total);
                pst.setString(7, bayar);
                pst.setString(8, kembali);
                pst.executeUpdate();
                tbData.setSelectedIndex(1);
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            }
            reset();
            tampil_data();
            }

            tampil_data();
            tbData.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        // TODO add your handling code here:
        String pilbar = cbBarang.getSelectedItem().toString();
        int harga = 0;
        switch (pilbar) {
            case "Buku" -> {
                eKode.setText("001");
                harga = 5000;
            }
            case "Bolpoin" -> {
                eKode.setText("002");
                harga = 3000;
            }
            case "Pensil" -> {
                eKode.setText("003");
                harga = 1500;
            }
            case "Penggaris" -> {
                eKode.setText("004");
                harga = 3000;
            }
            case "Penghapus" -> {
                eKode.setText("005");
                harga = 2000;
            }
            case "Sticky Note" -> {
                eKode.setText("006");
                harga = 8000;
            }
            default -> {
                eKode.setText("-");
                eHarga.setText("-");
            }
        }
         eHarga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cbBarangActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(eBayar.getText());

        // Ambil total harga dari komponen tampilan
        int totalHarga = Integer.parseInt(eTotal.getText());

        // Hitung kembalian
        int kembalian = bayar - totalHarga;

        if (kembalian < 0) {
            // Kembalian negatif, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Maaf, uang yang Anda bayarkan tidak mencukupi. Uang kurang sebesar: Rp " + Math.abs(kembalian));
            eKembalian.setText("Rp 0"); // Atur kembalian menjadi 0
        } else {
            // Tampilkan kembalian pada komponen tampilan eKembalian
            eKembalian.setText("Rp " + kembalian);
        }
    
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(eHarga.getText());
        int jumlah = Integer.parseInt(eJumlah.getText());

        // Hitung total harga
        int totalHarga = harga * jumlah;

        // Tampilkan total harga pada komponen tampilan eTotal
        eTotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbBarang.setSelectedIndex(0);
        eKode.setText(null);
        eHarga.setText(null);
        eNama.setText(null);
        eJumlah.setText(null);
        eTotal.setText(null);
        eBayar.setText(null);
        eKembalian.setText(null);
        btnSimpan.setText("Simpan");
        isEdit = false;
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblBarang.getSelectedRow();

        if (selectedRow != -1) {
            String pilbarValue = (String) tblBarang.getValueAt(selectedRow, 0);
            String kodeValue = (String) tblBarang.getValueAt(selectedRow, 1);
            String hargaValue = (String) tblBarang.getValueAt(selectedRow, 2);
            String namaValue = (String) tblBarang.getValueAt(selectedRow, 3);
            String jumlahValue = (String) tblBarang.getValueAt(selectedRow, 4);
            String totalValue = (String) tblBarang.getValueAt(selectedRow, 5);
            String bayarValue = (String) tblBarang.getValueAt(selectedRow, 6);
            String kembalianValue = (String) tblBarang.getValueAt(selectedRow, 7);

            cbBarang.setSelectedItem(pilbarValue);
            eKode.setText(kodeValue);
            eHarga.setText(hargaValue);
            eNama.setText(namaValue);
            eJumlah.setText(jumlahValue);
            eTotal.setText(totalValue);
            eBayar.setText(bayarValue);
            eKembalian.setText(kembalianValue);

            // Mengaktifkan tombol Edit
            btnSimpan.setText("Edit");
            isEdit = true; // Menandai bahwa ini adalah mode edit
        }

        
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pilihanuser = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
        if (pilihanuser == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JTextField eBayar;
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JTextField eKembalian;
    private javax.swing.JTextField eKode;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
